from server import Graph,node

if __name__ == "__main__":
    gra =  Graph()
    node1 = node(1)
    node2 = node(2)
    node3 = node(3)
    node4 = node(4)
    node5 = node(5)
    node6 = node(6)
    node7 = node(7)
    node8 = node(8)
    node9 = node(9)
    gra.nodes.append(node1)
    gra.nodes.append(node2)
    gra.nodes.append(node3)
    gra.nodes.append(node4)
    gra.nodes.append(node5)
    gra.nodes.append(node6)
    gra.nodes.append(node7)
    gra.nodes.append(node8)
    gra.nodes.append(node9)
    gra.add_link(node1,node2)
    gra.add_link(node2,node4)
    gra.add_link(node2,node3)
    gra.add_link(node3,node4)
    gra.add_link(node1,node5)
    gra.add_link(node4,node5)
    gra.add_link(node8,node5)
    gra.add_link(node9,node5)
    gra.add_link(node6,node9)
    gra.add_link(node6,node7)
    gra.add_link(node7,node8)
    gra.add_link(node7,node8)
    gra.add_link(node8,node9)
    distance,res = gra.dijkstra(node5)
